apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: fqaos3yz7-nodejs 
  janus-idp.io/tekton: fqaos3yz7-nodejs
  backstage.io/kubernetes-id: fqaos3yz7-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fqaos3yz7-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  